language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

before_install:
  - chmod +x install.sh

install:
  - pip install -r tests/requirements.txt
  - ./install.sh

script: "nosetests"
