---
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

before_install:
  - chmod +x install.sh

install:
  # development dependencies
  - pip install -r tests/requirements.txt
  - pip install --editable .
  - ./install.sh

# run tests
script: "nosetests"
